import Head from 'next/head'
import Header from "@/components/common/header";
import Home from '@/components/HomePage/home';
import Journey from '@/components/HomePage/Journey';
import Contact from '@/components/HomePage/Contact';
import AboutMe from '@/components/HomePage/AboutMe';

import Footer from '@/components/Footer/Footer';

export default function indexPage(props) {
  return (
    <>
      <Head>
        <title>Aditya Kumar </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header />
      <Home/>
      <AboutMe/>
      <Journey/>
      <Contact/>
      <Footer/>

    </>
  )
}


export const getServerSideProps =  async () => {
  // testing server side 
    try {
        return {
            props : {
                test :  []
            }
        }
    } catch(err) {}
    return {
        props : {
            error : true
        }
    }
}
