import Head from 'next/head'
import Header from "@/components/common/header";


export default function Home(props) {
  console.log(props)
  return (
    <>
      <Head>
        <title>Aditya Kumar </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

    </>
  )
}


export const getServerSideProps =  async () => {
    try {
        return {
            props : {
                test :  []
            }
        }
    } catch(err) {}
    return {
        props : {
            error : true
        }
    }
}
